### ISSUE TITLE
Cannot link to anon-running container (Gitlab CI environment)

### ISSUE THREAD

**Issue by Overdrivr** [frol/docker-alpine-gcc#4]
Hi,

I'd like to use this docker image inside a Gitlab Ci environment and run it as a service. (One of the python packages in my application needs g++ compiler).

Upon startup, I get the following error 

```
Running with gitlab-runner 10.0.0-rc.1 (6331f360) on docker-auto-scale (e11ae361)
Using Docker executor with image continuumio/anaconda3:4.4.0 ...
Starting service frolvlad/alpine-gcc:latest ...
Pulling docker image frolvlad/alpine-gcc:latest ...
Using docker image frolvlad/alpine-gcc:latest ID=sha256:6177fe49beef0cebf06dfa7d42b7c1438fd2fe3da54b2787de130e9c882c3444 for frolvlad/alpine-gcc service...
Waiting for services to be up and running...

*** WARNING: Service runner-e11ae361-project-3680280-concurrent-0-frolvlad__alpine-gcc-0 probably didn't start properly.

Error response from daemon: Cannot link to a non running container: /runner-e11ae361-project-3680280-concurrent-0-frolvlad__alpine-gcc-0 AS /runner-e11ae361-project-3680280-concurrent-0-frolvlad__alpine-gcc-0-wait-for-service/runner-e11ae361-project-3680280-concurrent-0-frolvlad__alpine-gcc-0

*********
```

Your docker image is started by the gitlab runner, I don't have much control on that

```
services:
  - frolvlad/alpine-gcc:latest

stages:
  - test
  - build

test:
  image: continuumio/anaconda3:4.4.0
  stage: test
  before_script:
    - python -V
    - pip -V
    - ... 
```

Any idea how I could fix this issue ? Thanks a lot
